In [1]:
from IPython.core.debugger import set_trace
import numpy as np
# mathjax docs: https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference

# The Problem

Given $A \in \mathbb{R}^{nxn} \text{ and } b \in \mathbb{R}^n$ in the equation:

$Ax = b$
  
We want to solve for $x$ 

In [2]:
A = np.random.random((3,3))
b = np.random.random((3,1))

# 1: Gausse Elimination

### No Pivoting:

In [18]:
AC = A.copy() # AC -> Copy of A
AC

array([[0.18197348, 0.42133452, 0.17584487],
       [0.92085066, 0.81153475, 0.40233247],
       [0.68967287, 0.04844981, 0.19093976]])

In [86]:
def expose_triangle(m):
    def expose_triangle_recurse(m, target_row, target_row_index, j):
        for row_i in range(target_row_index + 1, m.shape[0]):
            multiplier = np.divide( # to avoid divide by 0
                m[row_i][j], 
                target_row, 
                out=np.zeros_like(m[row_i]), 
                where= target_row != 0
            )
            calc = target_row * multiplier
            m[row_i] = np.abs(m[row_i]) - np.abs(calc)
            
        if j == m.shape[0]-1 or j >= m.shape[1]-1:
            return m
        else:
            return expose_triangle_recurse(m, m[target_row_index + 1], target_row_index + 1, j + 1)
    
    return expose_triangle_recurse(m, m[0], 0, 0)

In [136]:
g = np.random.uniform(0, 50, (4, 4))

print(g)
print("\n")
print(expose_triangle(g))

[[15.53457354 20.77697522 12.57700329 11.97382341]
 [24.59553811 18.56103987 19.96069982 40.65140447]
 [ 6.59056648 45.22696184 10.00187341 28.6352272 ]
 [ 1.74250819 38.60297985  2.00493572 39.47749635]]


[[ 15.53457354  20.77697522  12.57700329  11.97382341]
 [  0.          -6.03449825  -4.6348383   16.05586636]
 [  0.           0.         -35.22508843 -16.59173464]
 [  0.           0.           0.         -35.72352763]]


In [137]:
def no_pivot_gausse(A, b):
    pass